# Data

```{r}
#| include: false

library(tidyverse)
library(here)

library(fontawesome)


library(readxl)
creatinine <- read_excel(here("data", "creatinine.xlsx"))
depression <- read_excel(here("data", "depression.xlsx"))
weight <- read_excel(here("data", "weight.xlsx"))
dataDWL <- read_excel(here("data", "dataDWL.xlsx"))
prematurity <- read_excel(here("data", "prematurity.xlsx"))
LungCapacity <- read_excel(here("data", "LungCapacity.xlsx"))
```

   

-   **Dataset: creatinine**

```{r}
#| echo: false
#| label: fig-creatinine
#| fig-cap: Table with raw data.

DT::datatable(creatinine, extensions = c('Scroller', 'Buttons'), rownames = FALSE,
              options = list(deferRender = F, dom = 'Bt', scrollY = 452, scroller = TRUE, scrollX = T, pageLength = 10, buttons = 
      list(list(
        extend = 'csv',
        filename = 'creatinine'
      ), list(
        extend = 'excel',
        filename = 'creatinine',
        title = NULL
      ))))

```

   

-   **Dataset: depression**

```{r}
#| echo: false
#| label: fig-depression
#| fig-cap: Table with raw data.

DT::datatable(depression, extensions = c('Scroller', 'Buttons'), rownames = FALSE,
              options = list(deferRender = F, dom = 'Bt', scrollY = 452, scroller = TRUE, scrollX = T, pageLength = 10, buttons = 
      list(list(
        extend = 'csv',
        filename = 'depression'
      ), list(
        extend = 'excel',
        filename = 'depression',
        title = NULL
      ))))

```

   

-   **Dataset: weight**

```{r}
#| echo: false
#| label: fig-weight
#| fig-cap: Table with raw data.

DT::datatable(weight, extensions = c('Scroller', 'Buttons'), rownames = FALSE,
              options = list(deferRender = F, dom = 'Bt', scrollY = 452, scroller = TRUE, scrollX = T, pageLength = 10, buttons = 
      list(list(
        extend = 'csv',
        filename = 'weight'
      ), list(
        extend = 'excel',
        filename = 'weight',
        title = NULL
      ))))

```

   

-   **Dataset: dataDWL**

```{r}
#| echo: false
#| label: fig-dataDWL
#| fig-cap: Table with raw data.

DT::datatable(dataDWL, extensions = c('Scroller', 'Buttons'), rownames = FALSE,
              options = list(deferRender = F, dom = 'Bt', scrollY = 452, scroller = TRUE, scrollX = T, pageLength = 10, buttons = 
      list(list(
        extend = 'csv',
        filename = 'dataDWL'
      ), list(
        extend = 'excel',
        filename = 'dataDWL',
        title = NULL
      ))))

```

   

-   **Dataset: prematurity**

```{r}
#| echo: false
#| label: fig-prematurity
#| fig-cap: Table with raw data.

DT::datatable(prematurity, extensions = c('Scroller', 'Buttons'), rownames = FALSE,
              options = list(deferRender = F, dom = 'Bt', scrollY = 452, scroller = TRUE, scrollX = T, pageLength = 10, buttons = 
      list(list(
        extend = 'csv',
        filename = 'prematurity'
      ), list(
        extend = 'excel',
        filename = 'prematurity',
        title = NULL
      ))))

```


   

-   **Dataset: LungCapacity**

```{r}
#| echo: false
#| label: fig-LungCapacity
#| fig-cap: Table with raw data.

DT::datatable(LungCapacity, extensions = c('Scroller', 'Buttons'), rownames = FALSE,
              options = list(deferRender = F, dom = 'Bt', scrollY = 452, scroller = TRUE, scrollX = T, pageLength = 10, buttons = 
      list(list(
        extend = 'csv',
        filename = 'LungCapacity'
      ), list(
        extend = 'excel',
        filename = 'LungCapacity',
        title = NULL
      ))))
```

